.TH REDCLOTH 1 September 2011
.SH NAME
redcloth \- Ruby Textile formatter
.SH SYNOPSIS
redcloth [options] [redcloth_formatted.txt]
.SH DESCRIPTION
Format a Textile document into HTML or other type of output supported by
RedCloth. If no file specified, STDIN will be used. If you are typing
input, you can send an EOF by pressing ^D.
.SH OPTIONS
.TP
\fB-o\fR, \fB--output\fR \fBSTYLE\fR
Output format (defaults to html).
.SH AUTHOR
Dmitry Borodaenko <angdraug@debian.org>
.SH NOTES
This manual page was written by Dmitry Borodaenko <angdraug@debian.org>
for the Debian project.

This is free documentation; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 2 of the License, or (at your
option) any later version.
